### ISSUE TITLE
V2.0.3 issues with ES-Ver#2.4.0

### ISSUE THREAD

**Issue by aarvee11** [royrusso/elasticsearch-HQ#264]
# ./plugin install royrusso/elasticsearch-HQ/v2.0.3
-> Installing royrusso/elasticsearch-HQ/v2.0.3...
Trying https://download.elastic.co/royrusso/elasticsearch-HQ/elasticsearch-HQ-v2.0.3.zip ...
Trying https://search.maven.org/remotecontent?filepath=royrusso/elasticsearch-HQ/v2.0.3/elasticsearch-HQ-v2.0.3.zip ...
Trying https://oss.sonatype.org/service/local/repositories/releases/content/royrusso/elasticsearch-HQ/v2.0.3/elasticsearch-HQ-v2.0.3.zip ...
Trying https://github.com/royrusso/elasticsearch-HQ/archive/v2.0.3.zip ...
Downloading ......................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................DONE
Verifying https://github.com/royrusso/elasticsearch-HQ/archive/v2.0.3.zip checksums if available ...
NOTE: Unable to verify checksum for downloaded plugin (unable to find .sha1 or .md5 file to verify)
Installed hq into /usr/share/elasticsearch/plugins/hq

=====================================================
RESTARTING ELASTICSEARCH THROWS java.lang.IllegalStateException
=====================================================
[2016-09-30 13:29:52,512][ERROR][bootstrap                ] Exception
java.lang.IllegalStateException: Could not load plugin descriptor for existing plugin [hq]. Was the plugin built before 2.0?
	at org.elasticsearch.plugins.PluginsService.getPluginBundles(PluginsService.java:380)
	at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:128)
	at org.elasticsearch.node.Node.<init>(Node.java:158)
	at org.elasticsearch.node.Node.<init>(Node.java:140)
	at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:143)
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:194)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:286)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
Caused by: java.nio.file.AccessDeniedException: /usr/share/elasticsearch/plugins/hq/plugin-descriptor.properties
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.Files.newByteChannel(Files.java:361)
	at java.nio.file.Files.newByteChannel(Files.java:407)
	at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
	at java.nio.file.Files.newInputStream(Files.java:152)
	at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:87)
	at org.elasticsearch.plugins.PluginsService.getPluginBundles(PluginsService.java:378)
	... 7 more

**Comment by aarvee11** [comment]
It was a mere permissions issue! Closing the same
